# Generated by Django 4.2.5 on 2023-10-25 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='date',
        ),
    ]
