# Generated by Django 4.2.5 on 2023-10-29 23:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0003_song_unique_song_title_per_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='song',
            name='unique_song_title_per_user',
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('title', 'artist')},
        ),
    ]
