# Generated by Django 4.2.5 on 2023-10-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_remove_song_unique_song_title_per_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('title', 'artist'), name='unique_song_title_per_user'),
        ),
    ]
