# Generated by Django 4.2.5 on 2023-10-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_alter_song_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='song',
            name='unique_song_title_per_user',
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('title', 'artist'), name='unique_song_title_per_user', violation_error_message='your_error_message'),
        ),
    ]
