# Generated by Django 4.2.5 on 2023-11-09 03:32

import apps.player.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_remove_song_unique_song_title_per_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='song',
            name='unique_song_title_per_user',
        ),
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(apps.player.models.get_upload_path, *(), **{'folder_type': 'playlist'})),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('title', 'artist'), name='unique_album_title_per_user'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('title', 'artist'), name='unique_song_title_per_user'),
        ),
    ]
