# Generated by Django 4.2 on 2023-07-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='media/users/default.png', null=True, upload_to='users/'),
        ),
    ]
