# Generated by Django 4.2.5 on 2023-09-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_options_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='folder_path',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
