# Generated by Django 4.2.5 on 2023-09-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_folder_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['pk']},
        ),
    ]
