# Generated by Django 4.2.5 on 2023-10-03 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='folder_path',
        ),
    ]
